name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: deployment
    attributes:
      label: Deployment
      options:
        - Self-hosted (Docker)
        - Self-hosted (Manual)
        - Cloud (shipscope.dev)
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "Node version, OS, browser, etc."
